name: "Frogbot"
on:
  pull_request_target:
    types: [labeled, opened, reopened, synchronize]
jobs:
  scan-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Build Frogbot
        run: |
          git clone https://github.com/yahavi/frogbot.git
          cd frogbot
          git checkout verbose
          ./buildscripts/build.sh
      - name: Git status
        run: |
          git status
          git log --pretty=format:%s

      - name: Scan Pull Request
        env:
          JFROG_CLI_LOG_LEVEL: DEBUG
          JF_INSTALL_COMMAND: "npm i"
          JF_USER: ${{ secrets.JF_USER }}
          JF_URL: ${{ secrets.JF_URL }}
          JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
          JF_GIT_PROVIDER: github
          JF_GIT_OWNER: ${{ github.repository_owner }}
          JF_GIT_REPO: test-repo
          JF_GIT_TOKEN: ${{secrets.GITHUB_TOKEN}}
          JF_GIT_BASE_BRANCH: ${{ github.base_ref}}
          JF_GIT_PULL_REQUEST_ID: ${{ github.event.number }}
        run: ./frogbot/frogbot scan-pull-request
